"""replace test choices dict with list

Revision ID: 08831564fcf1
Revises: 170e478f46c7
Create Date: 2025-12-13 22:19:07.413985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08831564fcf1'
down_revision: Union[str, Sequence[str], None] = '170e478f46c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_questions",
        sa.Column(
            "choices_new",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default="{}",
        ),
    )
    op.execute("""
        UPDATE test_questions
        SET choices_new = ARRAY(
            SELECT value
            FROM jsonb_each_text(choices::jsonb)
            ORDER BY key
        )
    """)
    op.drop_column("test_questions", "choices")
    op.alter_column(
        "test_questions",
        "choices_new",
        new_column_name="choices",
    )
    op.alter_column(
        "test_questions",
        "choices",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_questions",
        sa.Column(
            "choices_old",
            postgresql.JSON(),
            nullable=False,
            server_default="{}",
        ),
    )
    op.execute("""
        UPDATE test_questions
        SET choices_old = (
            SELECT jsonb_object_agg(val, val)
            FROM unnest(choices) AS val
        )
    """)
    op.drop_column("test_questions", "choices")
    op.alter_column(
        "test_questions",
        "choices_old",
        new_column_name="choices",
    )
    # ### end Alembic commands ###
