"""replace test question name with number

Revision ID: 170e478f46c7
Revises: d0b4342b354e
Create Date: 2025-12-13 14:34:01.096742

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "170e478f46c7"
down_revision: Union[str, Sequence[str], None] = "d0b4342b354e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "test_questions", sa.Column("question_num", sa.Integer(), nullable=False)
    )
    # Удаляем ограничения только если они точно есть — или используем IF EXISTS
    op.execute(
        "ALTER TABLE test_questions DROP CONSTRAINT IF EXISTS test_questions_name_key"
    )
    op.execute(
        "ALTER TABLE test_questions DROP CONSTRAINT IF EXISTS test_questions_name_key1"
    )
    op.execute(
        "ALTER TABLE test_questions DROP CONSTRAINT IF EXISTS test_questions_name_key2"
    )
    op.drop_column("test_questions", "name")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_questions",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # op.create_unique_constraint(
    #     op.f("test_questions_name_key2"),
    #     "test_questions",
    #     ["name"],
    #     postgresql_nulls_not_distinct=False,
    # )
    # op.create_unique_constraint(
    #     op.f("test_questions_name_key1"),
    #     "test_questions",
    #     ["name"],
    #     postgresql_nulls_not_distinct=False,
    # )
    # op.create_unique_constraint(
    #     op.f("test_questions_name_key"),
    #     "test_questions",
    #     ["name"],
    #     postgresql_nulls_not_distinct=False,
    # )
    op.drop_column("test_questions", "question_num")
    # ### end Alembic commands ###
