"""add review model

Revision ID: 45a011eb0e1e
Revises: a079f25e1f58
Create Date: 2025-11-30 19:29:43.811982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a011eb0e1e'
down_revision: Union[str, Sequence[str], None] = 'a079f25e1f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_questions', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'test_questions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_questions', type_='unique')
    op.alter_column('test_questions', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
