"""update_user_course_model

Revision ID: ab4b851696c2
Revises: b60c8cd5995a
Create Date: 2025-12-08 20:47:28.939315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab4b851696c2'
down_revision: Union[str, Sequence[str], None] = 'b60c8cd5995a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lesson_progress')
    op.drop_column('user_courses', 'total_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_courses', sa.Column('total_progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_table('user_lesson_progress',
    sa.Column('user_course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.uuid'], name=op.f('user_lesson_progress_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_course_id'], ['user_courses.uuid'], name=op.f('user_lesson_progress_user_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_course_id', 'lesson_id', 'uuid', name=op.f('user_lesson_progress_pkey'))
    )
    # ### end Alembic commands ###
