"""update test questions

Revision ID: b60c8cd5995a
Revises: 814398e22e03
Create Date: 2025-12-05 23:12:21.629375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60c8cd5995a'
down_revision: Union[str, Sequence[str], None] = '814398e22e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_questions', 'lesson_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='lesson_id::uuid')
    op.create_foreign_key(None, 'test_questions', 'lessons', ['lesson_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.alter_column('test_questions', 'lesson_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='lesson_id::varchar')
    # ### end Alembic commands ###
