"""add user course model

Revision ID: c014f0b1de40
Revises: 4162245472ba
Create Date: 2025-12-05 22:13:01.341422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c014f0b1de40'
down_revision: Union[str, Sequence[str], None] = '4162245472ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_courses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('total_progress', sa.Float(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_lesson_progress',
    sa.Column('user_course_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('estimate', sa.Float(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_course_id'], ['user_courses.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_course_id', 'lesson_id', 'uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lesson_progress')
    op.drop_table('user_courses')
    # ### end Alembic commands ###
