"""Replace with a new syntax

Revision ID: d5a7411748f0
Revises: 0f92cd640d00
Create Date: 2025-11-30 14:18:52.554351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a7411748f0'
down_revision: Union[str, Sequence[str], None] = '0f92cd640d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('courses', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
